<a href="https://colab.research.google.com/github/arefin-nabil/fake_and_real_news_dataset_2026/blob/master/fake_news_yt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [133]:
import pandas as pd
import numpy as np

In [134]:
df_real = pd.read_csv("real_raw.csv", encoding='utf-8-sig')
df_fake = pd.read_csv("fake_raw.csv", encoding='utf-8-sig')

In [135]:
print("Real : ", df_real.shape)
print("Fake : ", df_fake.shape)

Real :  (2670, 7)
Fake :  (2685, 7)

In [136]:
print("Real : ", df_real.columns)
print("Fake : ", df_fake.columns)

Real :  Index(['title', 'text', 'source', 'publish_date', 'category', 'url', 'label'], dtype='object')
Fake :  Index(['title', 'text', 'source', 'publish_date', 'category', 'url', 'label'], dtype='object')

In [137]:
# real=0, fake=1
df_real['label'] = 0
df_fake['label'] = 1

In [138]:
df = pd.concat([df_real, df_fake], ignore_index=True)

In [139]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [140]:
print("Real and Fake : ", df.shape)

Real and Fake :  (5355, 7)

In [141]:
df['label'].value_counts()

label
1    2685
0    2670
Name: count, dtype: int64

In [142]:
df.isnull().sum()

title           0
text            0
source          0
publish_date    0
category        0
url             0
label           0
dtype: int64

In [143]:
df.to_csv("full_dataset.csv", index=False, encoding='utf-8-sig')

In [145]:
df.shape

(5355, 7)

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5355 entries, 0 to 5354
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         5355 non-null   object
 1   text          5355 non-null   object
 2   source        5355 non-null   object
 3   publish_date  5355 non-null   object
 4   category      5355 non-null   object
 5   url           5355 non-null   object
 6   label         5355 non-null   int64
dtypes: int64(1), object(6)
memory usage: 293.0+ KB

In [153]:
df_dl = df[['title', 'text', 'label']].copy()

df_dl.to_csv("dl_dataset.csv", index=False, encoding='utf-8-sig')

In [148]:
df_dl.shape

(5355, 3)

In [149]:
from google.colab import files
files.download("full_dataset.csv")
files.download("dl_dataset.csv")